### ISSUE TITLE
CSS中一个元素hover，如何改变其他元素样式？

### ISSUE THREAD

**Issue by wpfalive** [wpfalive/wpfalive.github.io#2]
[知乎的回答](https://www.zhihu.com/question/30950379)
[张鑫旭的回答](https://www.zhangxinxu.com/wordpress/2016/08/css-parent-selector/)

如果被hover的元素为a, 

1. b是a的直接子元素，那么可以用 `a:hover > b {...style}`
2. b是紧邻着a的兄弟元素，那么可以用 `a:hover + b {...style}`
3. b是a后面的兄弟元素，那么可以用 `a:hover ~ b {...style}`

举个例子：
```html
<div id="app">
    <div class="in1"></div>
    <div class="in2"></div>
    <div class="in3"></div>
  </div>
```

```css
#app div {
  height: 100px;
  border: 1px solid black;
  margin: 2px;
}

#app .in1 {
  border: 1px solid red;
}
#app .in1:hover {
  border: 1px solid blue;
}

#app .in1:hover ~ div {
  border: 1px solid yellow;
}
```
效果是这样的：
![image](https://user-images.githubusercontent.com/15048423/41569560-1af6f5ca-739e-11e8-8651-78411d47d25c.png)

当第一个div被hover时，后面两个兄弟div border变为黄色。
